--------------------------------------------------------
--  Fichier créé - jeudi-mars-11-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "AZIZ"."CLIENT" 
   (	"CIN_CLIENT" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TELEPHONE" NUMBER, 
	"POINTS_FIDELITE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "AZIZ"."COMMANDE" 
   (	"ID_COMMANDE" VARCHAR2(20 BYTE), 
	"CIN_CLINET" VARCHAR2(8 BYTE), 
	"QUANTITE" NUMBER, 
	"ID_PRODUIT" NUMBER, 
	"DATE_COMMANDE" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CIN_EMPLOYE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "AZIZ"."CONGE" 
   (	"CIN_EMPLOYE" VARCHAR2(8 BYTE), 
	"DATE_DEPART" DATE, 
	"DATE_RETOUR" DATE, 
	"NATURE" VARCHAR2(20 BYTE), 
	"CONFIRMATION" VARCHAR2(20 BYTE), 
	"ID_CONGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "AZIZ"."EMPLOYE" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TELEPHONE" NUMBER, 
	"ROLE" VARCHAR2(20 BYTE), 
	"EVALUATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "AZIZ"."EQUIPEMENT" 
   (	"ID_EQUIPEMENT" NUMBER DEFAULT 1, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"CARACTERISTIQUE" VARCHAR2(20 BYTE), 
	"DATE_ACHAT" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVALUATION
--------------------------------------------------------

  CREATE TABLE "AZIZ"."EVALUATION" 
   (	"ID_EVALUATION" NUMBER, 
	"AUTONOMIE" VARCHAR2(20 BYTE), 
	"PERFORMANCE" VARCHAR2(20 BYTE), 
	"FIABILITE" VARCHAR2(20 BYTE), 
	"COMMENTAIRE" VARCHAR2(255 BYTE), 
	"DATE_EVALUATION" VARCHAR2(20 BYTE), 
	"CIN_EMPLOYE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "AZIZ"."EVENEMENT" 
   (	"ID_EVENEMENT" NUMBER, 
	"NOM_EVENEMENT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"BUDGET" NUMBER, 
	"LIEU" VARCHAR2(20 BYTE), 
	"NOMBRE_INVITE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "AZIZ"."FOURNISSEUR" 
   (	"ID_FOURNISSEUR" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TELEPHONE" NUMBER, 
	"SPECIALITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "AZIZ"."PARTICIPANTS" 
   (	"ID_PARTICIPANT" NUMBER, 
	"ID_EVENEMENT" NUMBER, 
	"CIN_EMPLOYE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "AZIZ"."PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"PRIX" NUMBER, 
	"DATE_EXPIRATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETTE
--------------------------------------------------------

  CREATE TABLE "AZIZ"."RECETTE" 
   (	"ID_RECETTE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"NOMBRE_INGREDIENT" NUMBER, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"ID_PRODUIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "AZIZ"."RECLAMATION" 
   (	"ID_RECLAMATION" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"DATE_RECLAMATION" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"TITRE" VARCHAR2(20 BYTE), 
	"CIN_EMPLOYE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPARATEUR
--------------------------------------------------------

  CREATE TABLE "AZIZ"."REPARATEUR" 
   (	"ID_REPARATEUR" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"TELEPHONE" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"SOCIETE" VARCHAR2(20 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPARATION
--------------------------------------------------------

  CREATE TABLE "AZIZ"."REPARATION" 
   (	"ID_PANNE" NUMBER, 
	"ID_EQUIPEMENT" NUMBER, 
	"ID_REPARATEUR" NUMBER, 
	"NOM_EQUIPEMENT" VARCHAR2(20 BYTE), 
	"PRIX_REPARATION" NUMBER, 
	"DATE_LIVRAISON" DATE, 
	"DATE_RECEPTION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "AZIZ"."STOCK" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"ID_FOURNISSEUR" NUMBER, 
	"NOM_MP" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"DATE_ACHAT" DATE, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AZIZ.CLIENT
SET DEFINE OFF;
REM INSERTING into AZIZ.COMMANDE
SET DEFINE OFF;
REM INSERTING into AZIZ.CONGE
SET DEFINE OFF;
REM INSERTING into AZIZ.EMPLOYE
SET DEFINE OFF;
REM INSERTING into AZIZ.EQUIPEMENT
SET DEFINE OFF;
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('3','2','2','2','01/01/2000','2','2');
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('4','2','2','2','01/01/2000','2','2');
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('5','dsq','0','sdq','01/01/2000','ds','dsqd');
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('6',null,'0',null,'01/01/2000',null,null);
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('7',null,'0',null,'01/01/2000',null,null);
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('8','zz','2','qs','01/01/2000','sq','QSD');
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('1','2','2','2','01/01/2000','2','2');
Insert into AZIZ.EQUIPEMENT (ID_EQUIPEMENT,NOM,PRIX,CARACTERISTIQUE,DATE_ACHAT,MARQUE,ETAT) values ('2','2','2','2','01/01/2000','2','2');
REM INSERTING into AZIZ.EVALUATION
SET DEFINE OFF;
REM INSERTING into AZIZ.EVENEMENT
SET DEFINE OFF;
REM INSERTING into AZIZ.FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into AZIZ.PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into AZIZ.PRODUIT
SET DEFINE OFF;
REM INSERTING into AZIZ.RECETTE
SET DEFINE OFF;
REM INSERTING into AZIZ.RECLAMATION
SET DEFINE OFF;
REM INSERTING into AZIZ.REPARATEUR
SET DEFINE OFF;
REM INSERTING into AZIZ.REPARATION
SET DEFINE OFF;
REM INSERTING into AZIZ.STOCK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."COMMANDE_PK" ON "AZIZ"."COMMANDE" ("ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."FOURNISSEUR_PK" ON "AZIZ"."FOURNISSEUR" ("ID_FOURNISSEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."PRODUIT_PK" ON "AZIZ"."PRODUIT" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."STOCK_PK" ON "AZIZ"."STOCK" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVALUATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."EVALUATION_PK" ON "AZIZ"."EVALUATION" ("ID_EVALUATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."EVENEMENT_PK" ON "AZIZ"."EVENEMENT" ("ID_EVENEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPARATEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."REPARATEUR_PK" ON "AZIZ"."REPARATEUR" ("ID_REPARATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."CONGE_PK" ON "AZIZ"."CONGE" ("ID_CONGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPARATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."REPARATION_PK" ON "AZIZ"."REPARATION" ("ID_PANNE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECETTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."RECETTE_PK" ON "AZIZ"."RECETTE" ("ID_RECETTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."EQUIPEMENT_PK" ON "AZIZ"."EQUIPEMENT" ("ID_EQUIPEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PL_CIN_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."PL_CIN_EMPLOYE" ON "AZIZ"."EMPLOYE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTICIPANTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."PARTICIPANTS_PK" ON "AZIZ"."PARTICIPANTS" ("ID_PARTICIPANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."RECLAMATION_PK" ON "AZIZ"."RECLAMATION" ("ID_RECLAMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CIN_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."PK_CIN_CLIENT" ON "AZIZ"."CLIENT" ("CIN_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Package EQUIPEMENT_TAPI
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "AZIZ"."EQUIPEMENT_TAPI" 
is

type EQUIPEMENT_tapi_rec is record (
ETAT  EQUIPEMENT.ETAT%type
,PRIX  EQUIPEMENT.PRIX%type
,CARACTERISTIQUE  EQUIPEMENT.CARACTERISTIQUE%type
,DATE_ACHAT  EQUIPEMENT.DATE_ACHAT%type
,ID_EQUIPEMENT  EQUIPEMENT.ID_EQUIPEMENT%type
,MARQUE  EQUIPEMENT.MARQUE%type
,NOM  EQUIPEMENT.NOM%type
);
type EQUIPEMENT_tapi_tab is table of EQUIPEMENT_tapi_rec;

-- insert
procedure ins (
p_ETAT in EQUIPEMENT.ETAT%type default null 
,p_PRIX in EQUIPEMENT.PRIX%type default null 
,p_CARACTERISTIQUE in EQUIPEMENT.CARACTERISTIQUE%type default null 
,p_DATE_ACHAT in EQUIPEMENT.DATE_ACHAT%type default null 
,p_ID_EQUIPEMENT in EQUIPEMENT.ID_EQUIPEMENT%type AUTO_INCREMENT
,p_MARQUE in EQUIPEMENT.MARQUE%type default null 
,p_NOM in EQUIPEMENT.NOM%type default null 
);
-- update
procedure upd (
p_ETAT in EQUIPEMENT.ETAT%type default null 
,p_PRIX in EQUIPEMENT.PRIX%type default null 
,p_CARACTERISTIQUE in EQUIPEMENT.CARACTERISTIQUE%type default null 
,p_DATE_ACHAT in EQUIPEMENT.DATE_ACHAT%type default null 
,p_ID_EQUIPEMENT in EQUIPEMENT.ID_EQUIPEMENT%type
,p_MARQUE in EQUIPEMENT.MARQUE%type default null 
,p_NOM in EQUIPEMENT.NOM%type default null 
);
-- delete
procedure del (
p_ID_EQUIPEMENT in EQUIPEMENT.ID_EQUIPEMENT%type
);
end EQUIPEMENT_tapi;


/
--------------------------------------------------------
--  DDL for Package Body EQUIPEMENT_TAPI
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "AZIZ"."EQUIPEMENT_TAPI" 
is
-- insert
procedure ins (
p_ETAT in EQUIPEMENT.ETAT%type default null 
,p_PRIX in EQUIPEMENT.PRIX%type default null 
,p_CARACTERISTIQUE in EQUIPEMENT.CARACTERISTIQUE%type default null 
,p_DATE_ACHAT in EQUIPEMENT.DATE_ACHAT%type default null 
,p_ID_EQUIPEMENT in EQUIPEMENT.ID_EQUIPEMENT%type
,p_MARQUE in EQUIPEMENT.MARQUE%type default null 
,p_NOM in EQUIPEMENT.NOM%type default null 
) is
begin
insert into EQUIPEMENT(
ETAT
,PRIX
,CARACTERISTIQUE
,DATE_ACHAT
,ID_EQUIPEMENT
,MARQUE
,NOM
) values (
p_ETAT
,p_PRIX
,p_CARACTERISTIQUE
,p_DATE_ACHAT
,p_ID_EQUIPEMENT
,p_MARQUE
,p_NOM
);end;
-- update
procedure upd (
p_ETAT in EQUIPEMENT.ETAT%type default null 
,p_PRIX in EQUIPEMENT.PRIX%type default null 
,p_CARACTERISTIQUE in EQUIPEMENT.CARACTERISTIQUE%type default null 
,p_DATE_ACHAT in EQUIPEMENT.DATE_ACHAT%type default null 
,p_ID_EQUIPEMENT in EQUIPEMENT.ID_EQUIPEMENT%type
,p_MARQUE in EQUIPEMENT.MARQUE%type default null 
,p_NOM in EQUIPEMENT.NOM%type default null 
) is
begin
update EQUIPEMENT set
ETAT = p_ETAT
,PRIX = p_PRIX
,CARACTERISTIQUE = p_CARACTERISTIQUE
,DATE_ACHAT = p_DATE_ACHAT
,MARQUE = p_MARQUE
,NOM = p_NOM
where ID_EQUIPEMENT = p_ID_EQUIPEMENT;
end;
-- del
procedure del (
p_ID_EQUIPEMENT in EQUIPEMENT.ID_EQUIPEMENT%type
) is
begin
delete from EQUIPEMENT
where ID_EQUIPEMENT = p_ID_EQUIPEMENT;
end;
end EQUIPEMENT_tapi;

/
--------------------------------------------------------
--  Constraints for Table RECETTE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."RECETTE" ADD CONSTRAINT "RECETTE_PK" PRIMARY KEY ("ID_RECETTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."RECETTE" MODIFY ("ID_RECETTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_PK" PRIMARY KEY ("ID_PARTICIPANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."PARTICIPANTS" MODIFY ("ID_PARTICIPANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "AZIZ"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("ID_RECLAMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."RECLAMATION" MODIFY ("ID_RECLAMATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."COMMANDE" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVALUATION
--------------------------------------------------------

  ALTER TABLE "AZIZ"."EVALUATION" ADD CONSTRAINT "EVALUATION_PK" PRIMARY KEY ("ID_EVALUATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."EVALUATION" MODIFY ("ID_EVALUATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."PRODUIT" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPARATEUR
--------------------------------------------------------

  ALTER TABLE "AZIZ"."REPARATEUR" ADD CONSTRAINT "REPARATEUR_PK" PRIMARY KEY ("ID_REPARATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."REPARATEUR" MODIFY ("ID_REPARATEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPARATION
--------------------------------------------------------

  ALTER TABLE "AZIZ"."REPARATION" ADD CONSTRAINT "REPARATION_PK" PRIMARY KEY ("ID_PANNE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."REPARATION" MODIFY ("ID_PANNE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."CONGE" ADD CONSTRAINT "CONGE_PK" PRIMARY KEY ("ID_CONGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."CONGE" MODIFY ("ID_CONGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."EVENEMENT" ADD CONSTRAINT "EVENEMENT_PK" PRIMARY KEY ("ID_EVENEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."EVENEMENT" MODIFY ("ID_EVENEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("ID_EQUIPEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."EQUIPEMENT" MODIFY ("ID_EQUIPEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "AZIZ"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID_FOURNISSEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."FOURNISSEUR" MODIFY ("ID_FOURNISSEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "AZIZ"."STOCK" ADD CONSTRAINT "STOCK_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."STOCK" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."CLIENT" ADD CONSTRAINT "PK_CIN_CLIENT" PRIMARY KEY ("CIN_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."CLIENT" MODIFY ("CIN_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."EMPLOYE" ADD CONSTRAINT "PL_CIN_EMPLOYE" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_FK1" FOREIGN KEY ("ID_PRODUIT")
	  REFERENCES "AZIZ"."PRODUIT" ("ID_PRODUIT") ENABLE;
  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_FK2" FOREIGN KEY ("CIN_CLINET")
	  REFERENCES "AZIZ"."CLIENT" ("CIN_CLIENT") ENABLE;
  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_FK3" FOREIGN KEY ("CIN_EMPLOYE")
	  REFERENCES "AZIZ"."EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."CONGE" ADD CONSTRAINT "CONGE_FK" FOREIGN KEY ("CIN_EMPLOYE")
	  REFERENCES "AZIZ"."EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVALUATION
--------------------------------------------------------

  ALTER TABLE "AZIZ"."EVALUATION" ADD CONSTRAINT "EVALUATION_FK1" FOREIGN KEY ("CIN_EMPLOYE")
	  REFERENCES "AZIZ"."EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "AZIZ"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_FK1" FOREIGN KEY ("ID_EVENEMENT")
	  REFERENCES "AZIZ"."EVENEMENT" ("ID_EVENEMENT") ENABLE;
  ALTER TABLE "AZIZ"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_FK2" FOREIGN KEY ("CIN_EMPLOYE")
	  REFERENCES "AZIZ"."EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECETTE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."RECETTE" ADD CONSTRAINT "RECETTE_FK1" FOREIGN KEY ("ID_PRODUIT")
	  REFERENCES "AZIZ"."PRODUIT" ("ID_PRODUIT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "AZIZ"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_FK1" FOREIGN KEY ("CIN_EMPLOYE")
	  REFERENCES "AZIZ"."EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPARATION
--------------------------------------------------------

  ALTER TABLE "AZIZ"."REPARATION" ADD CONSTRAINT "REPARATION_FK2" FOREIGN KEY ("ID_REPARATEUR")
	  REFERENCES "AZIZ"."REPARATEUR" ("ID_REPARATEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "AZIZ"."STOCK" ADD CONSTRAINT "STOCK_FK1" FOREIGN KEY ("ID_FOURNISSEUR")
	  REFERENCES "AZIZ"."FOURNISSEUR" ("ID_FOURNISSEUR") ENABLE;
